Update delete.yml

diff --git a/.github/workflows/delete.yml b/.github/workflows/delete.yml
--- a/.github/workflows/delete.yml
+++ b/.github/workflows/delete.yml
@@ -2,13 +2,9 @@ name: Delete Old Workflow Runs
 
 on:
   workflow_dispatch:
-    inputs:
-      workflowName:
-        description: 'Name of the workflow to delete runs for'
-        required: false
   push:
     branches:
-      - main # Your feature branch
+      - main
 
 jobs:
   delete-runs:
@@ -22,32 +18,31 @@ jobs:
       run: |
         curl -sSL https://github.com/cli/cli/releases/download/v2.2.0/gh_2.2.0_linux_amd64.tar.gz | tar xz -C /tmp
         sudo mv /tmp/gh_*/bin/gh /usr/local/bin/
-        
+
     - name: Authenticate GitHub CLI
       run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
 
     - name: Delete Runs
       run: |
         repo="${{ github.repository }}"
-        workflow="${{ github.event.inputs.workflowName || 'default-workflow.yml' }}"
+        workflow="${{ github.event.inputs.workflowName }}" # You'll need to specify this as an input if you use workflow_dispatch
         page_size=50
         page_number=1
         while : ; do
-          if ! run_ids=$(gh api -X GET "/repos/$repo/actions/workflows/$workflow/runs?per_page=$page_size&page=$page_number" --jq '.workflow_runs[] | select(.id != null) | .id'); then
+          run_ids=$(gh api -X GET "/repos/$repo/actions/workflows/$workflow/runs?per_page=$page_size&page=$page_number" --jq '.workflow_runs[] | select(.id != null) | .id')
+          if [[ -z "$run_ids" ]]; then
             echo "No more runs found."
             break
           fi
           for run_id in $run_ids; do
-            [[ "$run_id" =~ ^[0-9]+$ ]] || continue
-            echo "Deleting run id $run_id"
-            error_message=$(gh run delete $run_id --repo $repo 2>&1 >/dev/null)
-            case "$error_message" in
-              *"gh: Not Found (HTTP 404)"*) 
-                echo "Stopping script due to 404 error."
-                exit 1
-                ;;
-              *) ;;  
-            esac
+            if [[ "$run_id" =~ ^[0-9]+$ ]]; then
+              echo "Deleting run id $run_id"
+              error_message=$(gh run delete $run_id --repo $repo 2>&1 >/dev/null)
+              if [[ $error_message == *"gh: Not Found (HTTP 404)"* ]]; then
+                echo "Encountered 404 error. Skipping..."
+                # exit 1  # Uncomment this if you want to stop the script on 404
+              fi
+            fi
             sleep 2  
           done
           ((page_number++))
